# 使用官方Go镜像作为父镜像
FROM golang:1.20-alpine

# 设置代理环境
RUN go env -w GO111MODULE=auto \
  && go env -w CGO_ENABLED=0 \
  && go env -w GOPROXY=https://goproxy.cn,direct

# 设置工作目录
WORKDIR /app

# 将go.mod和go.sum文件复制到工作目录
COPY go.mod go.sum ./

# 下载所有依赖
RUN go mod download

# 将项目源代码复制到工作目录
COPY . .

# 构建Go应用程序
RUN go build -o main .


# 使端口8080可供此容器外的环境使用
EXPOSE 8080

# 在容器启动时运行Go应用程序
CMD ["./main server"]